#!/bin/bash

if [[ -z $1 || $1 == "--help" || $1 == "-h" || $1 == "help" ]]; then
	echo ""
	echo "Avahi stopper script"
	echo " --start	start avahi-daemon"
	echo " --stop	stop avahi-daemon"
	echo ""
elif [[ $1 = '--start' ]]; then
	sudo systemctl enable avahi-daemon.socket avahi-daemon
	sudo systemctl start avahi-daemon.socket avahi-daemon
	echo "Done."
elif [[ $1 = '--stop' ]]; then
	sudo systemctl disable avahi-daemon.socket avahi-daemon
	sudo systemctl stop avahi-daemon.socket avahi-daemon
	echo "Done."
else
	echo "unknown option"
	echo "call 'avahi --help' for more info"
fi
exit
